permissions:
  contents: write

steps:
  - name: Generate github-contribution-grid-snake.svg
    uses: Platane/snk/svg-only@v3
    with:
      github_user_name: ${{ github.repository_owner }}
      outputs: |
        dist/github-contribution-grid-snake.svg?color_snake=#D4AF37&color_dots=#0B0B12,#1A1225,#3B5240,#6B4E71,#C9A0DC
      
  - name: Push to output branch
    # 🔮 MANTRA BARU: Upgrade ke v4 agar tidak error Node.js 20 Deprecated
    uses: crazy-max/ghaction-github-pages@v4
    with:
      target_branch: output
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
